#!/bin/sh -e

cd mac
rm -rf build/Release
xcodebuild -project Free42.xcodeproj -target "Free42 Binary" -configuration Release build
xcodebuild -project Free42.xcodeproj -target "Free42 Decimal" -configuration Release build
mkdir tmp
mv "build/Release/Free42 Binary.app" tmp
mv "build/Release/Free42 Decimal.app" tmp
cp README.txt tmp
cd tmp
zip -r ../../Free42Mac.zip "Free42 Binary.app" "Free42 Decimal.app" README.txt
cd ..
rm -rf tmp
cd ..
