copy ..\common\free42.h .
copy ..\common\core_commands1.cc .
copy ..\common\core_commands1.h .
copy ..\common\core_commands2.cc .
copy ..\common\core_commands2.h .
copy ..\common\core_commands3.cc .
copy ..\common\core_commands3.h .
copy ..\common\core_commands4.cc .
copy ..\common\core_commands4.h .
copy ..\common\core_commands5.cc .
copy ..\common\core_commands5.h .
copy ..\common\core_commands6.cc .
copy ..\common\core_commands6.h .
copy ..\common\core_display.cc .
copy ..\common\core_display.h .
copy ..\common\core_globals.cc .
copy ..\common\core_globals.h .
copy ..\common\core_helpers.cc .
copy ..\common\core_helpers.h .
copy ..\common\core_keydown.cc .
copy ..\common\core_keydown.h .
copy ..\common\core_linalg1.cc .
copy ..\common\core_linalg1.h .
copy ..\common\core_linalg2.cc .
copy ..\common\core_linalg2.h .
copy ..\common\core_math1.cc .
copy ..\common\core_math1.h .
copy ..\common\core_math2.cc .
copy ..\common\core_math2.h .
copy ..\common\core_main.cc .
copy ..\common\core_main.h .
copy ..\common\core_phloat.cc .
copy ..\common\core_phloat.h .
copy ..\common\core_sto_rcl.cc .
copy ..\common\core_sto_rcl.h .
copy ..\common\core_tables.cc .
copy ..\common\core_tables.h .
copy ..\common\core_variables.cc .
copy ..\common\core_variables.h .
copy ..\common\shell.h .
copy ..\common\shell_loadimage.cc .
copy ..\common\shell_loadimage.h .
copy ..\common\shell_spool.cc .
copy ..\common\shell_spool.h .
copy ..\common\skin2cc.cc .
copy ..\common\skin2cc.conf .
copy ..\common\keymap2cc.cc .
copy ..\util\rom2raw.c .
