copy free42.h ..\common
copy core_commands1.cpp ..\common\core_commands1.cc
copy core_commands1.h ..\common
copy core_commands2.cpp ..\common\core_commands2.cc
copy core_commands2.h ..\common
copy core_commands3.cpp ..\common\core_commands3.cc
copy core_commands3.h ..\common
copy core_commands4.cpp ..\common\core_commands4.cc
copy core_commands4.h ..\common
copy core_commands5.cpp ..\common\core_commands5.cc
copy core_commands5.h ..\common
copy core_commands6.cpp ..\common\core_commands6.cc
copy core_commands6.h ..\common
copy core_commands7.cpp ..\common\core_commands7.cc
copy core_commands7.h ..\common
copy core_display.cpp ..\common\core_display.cc
copy core_display.h ..\common
copy core_globals.cpp ..\common\core_globals.cc
copy core_globals.h ..\common
copy core_helpers.cpp ..\common\core_helpers.cc
copy core_helpers.h ..\common
copy core_keydown.cpp ..\common\core_keydown.cc
copy core_keydown.h ..\common
copy core_linalg1.cpp ..\common\core_linalg1.cc
copy core_linalg1.h ..\common
copy core_linalg2.cpp ..\common\core_linalg2.cc
copy core_linalg2.h ..\common
copy core_math1.cpp ..\common\core_math1.cc
copy core_math1.h ..\common
copy core_math2.cpp ..\common\core_math2.cc
copy core_math2.h ..\common
copy core_main.cpp ..\common\core_main.cc
copy core_main.h ..\common
copy core_phloat.cpp ..\common\core_phloat.cc
copy core_phloat.h ..\common
copy core_sto_rcl.cpp ..\common\core_sto_rcl.cc
copy core_sto_rcl.h ..\common
copy core_tables.cpp ..\common\core_tables.cc
copy core_tables.h ..\common
copy core_variables.cpp ..\common\core_variables.cc
copy core_variables.h ..\common
copy shell.h ..\common
copy shell_loadimage.cpp ..\common\shell_loadimage.cc
copy shell_loadimage.h ..\common
copy shell_spool.cpp ..\common\shell_spool.cc
copy shell_spool.h ..\common
copy skin2cpp.cpp ..\common\skin2cc.cc
copy skin2cpp.conf ..\common\skin2cc.conf
copy keymap2cpp.cpp ..\common\keymap2cc.cc
copy bid_conf.h ..\common
copy bid_functions.h ..\common
