copy ..\common\free42.h .
copy ..\common\core_commands1.cc core_commands1.cpp
copy ..\common\core_commands1.h .
copy ..\common\core_commands2.cc core_commands2.cpp
copy ..\common\core_commands2.h .
copy ..\common\core_commands3.cc core_commands3.cpp
copy ..\common\core_commands3.h .
copy ..\common\core_commands4.cc core_commands4.cpp
copy ..\common\core_commands4.h .
copy ..\common\core_commands5.cc core_commands5.cpp
copy ..\common\core_commands5.h .
copy ..\common\core_commands6.cc core_commands6.cpp
copy ..\common\core_commands6.h .
copy ..\common\core_commands7.cc core_commands7.cpp
copy ..\common\core_commands7.h .
copy ..\common\core_display.cc core_display.cpp
copy ..\common\core_display.h .
copy ..\common\core_globals.cc core_globals.cpp
copy ..\common\core_globals.h .
copy ..\common\core_helpers.cc core_helpers.cpp
copy ..\common\core_helpers.h .
copy ..\common\core_keydown.cc core_keydown.cpp
copy ..\common\core_keydown.h .
copy ..\common\core_linalg1.cc core_linalg1.cpp
copy ..\common\core_linalg1.h .
copy ..\common\core_linalg2.cc core_linalg2.cpp
copy ..\common\core_linalg2.h .
copy ..\common\core_math1.cc core_math1.cpp
copy ..\common\core_math1.h .
copy ..\common\core_math2.cc core_math2.cpp
copy ..\common\core_math2.h .
copy ..\common\core_main.cc core_main.cpp
copy ..\common\core_main.h .
copy ..\common\core_phloat.cc core_phloat.cpp
copy ..\common\core_phloat.h .
copy ..\common\core_sto_rcl.cc core_sto_rcl.cpp
copy ..\common\core_sto_rcl.h .
copy ..\common\core_tables.cc core_tables.cpp
copy ..\common\core_tables.h .
copy ..\common\core_variables.cc core_variables.cpp
copy ..\common\core_variables.h .
copy ..\common\shell.h .
copy ..\common\shell_loadimage.cc shell_loadimage.cpp
copy ..\common\shell_loadimage.h .
copy ..\common\shell_spool.cc shell_spool.cpp
copy ..\common\shell_spool.h .
copy ..\common\skin2cc.cc skin2cpp.cpp
copy ..\common\skin2cc.conf skin2cpp.conf
copy ..\common\keymap2cc.cc keymap2cpp.cpp
copy ..\common\bid_conf.h .
copy ..\common\bid_functions.h .
