copy free42.h ..\common
copy core_commands1.cc ..\common
copy core_commands1.h ..\common
copy core_commands2.cc ..\common
copy core_commands2.h ..\common
copy core_commands3.cc ..\common
copy core_commands3.h ..\common
copy core_commands4.cc ..\common
copy core_commands4.h ..\common
copy core_commands5.cc ..\common
copy core_commands5.h ..\common
copy core_commands6.cc ..\common
copy core_commands6.h ..\common
copy core_display.cc ..\common
copy core_display.h ..\common
copy core_globals.cc ..\common
copy core_globals.h ..\common
copy core_helpers.cc ..\common
copy core_helpers.h ..\common
copy core_keydown.cc ..\common
copy core_keydown.h ..\common
copy core_linalg1.cc ..\common
copy core_linalg1.h ..\common
copy core_linalg2.cc ..\common
copy core_linalg2.h ..\common
copy core_math1.cc ..\common
copy core_math1.h ..\common
copy core_math2.cc ..\common
copy core_math2.h ..\common
copy core_main.cc ..\common
copy core_main.h ..\common
copy core_phloat.cc ..\common
copy core_phloat.h ..\common
copy core_sto_rcl.cc ..\common
copy core_sto_rcl.h ..\common
copy core_tables.cc ..\common
copy core_tables.h ..\common
copy core_variables.cc ..\common
copy core_variables.h ..\common
copy shell.h ..\common
copy shell_loadimage.cc ..\common
copy shell_loadimage.h ..\common
copy shell_spool.cc ..\common
copy shell_spool.h ..\common
copy skin2cc.cc ..\common
copy skin2cc.conf ..\common
copy keymap2cc.cc ..\common
copy bcd.cc ..\common
copy bcd.h ..\common
copy bcdfloat.cc ..\common
copy bcdfloat.h ..\common
copy bcdmath.cc ..\common
copy bcdmath.h ..\common
copy rom2raw.c ..\util
