del free42.h
del core_commands1.cc
del core_commands1.h
del core_commands2.cc
del core_commands2.h
del core_commands3.cc
del core_commands3.h
del core_commands4.cc
del core_commands4.h
del core_commands5.cc
del core_commands5.h
del core_commands6.cc
del core_commands6.h
del core_decimal.cc
del core_decimal.h
del core_display.cc
del core_display.h
del core_globals.cc
del core_globals.h
del core_helpers.cc
del core_helpers.h
del core_keydown.cc
del core_keydown.h
del core_linalg1.cc
del core_linalg1.h
del core_linalg2.cc
del core_linalg2.h
del core_math1.cc
del core_math1.h
del core_math2.cc
del core_math2.h
del core_main.cc
del core_main.h
del core_phloat.cc
del core_phloat.h
del core_sto_rcl.cc
del core_sto_rcl.h
del core_tables.cc
del core_tables.h
del core_variables.cc
del core_variables.h
del shell.h
del shell_loadimage.cc
del shell_loadimage.h
del shell_spool.cc
del shell_spool.h
del skin2cc.cc
del skin2cc.conf
del keymap2cc.cc
del rom2raw.c
