del free42.h
del core_commands1.cpp
del core_commands1.h
del core_commands2.cpp
del core_commands2.h
del core_commands3.cpp
del core_commands3.h
del core_commands4.cpp
del core_commands4.h
del core_commands5.cpp
del core_commands5.h
del core_commands6.cpp
del core_commands6.h
del core_commands7.cpp
del core_commands7.h
del core_display.cpp
del core_display.h
del core_globals.cpp
del core_globals.h
del core_helpers.cpp
del core_helpers.h
del core_keydown.cpp
del core_keydown.h
del core_linalg1.cpp
del core_linalg1.h
del core_linalg2.cpp
del core_linalg2.h
del core_math1.cpp
del core_math1.h
del core_math2.cpp
del core_math2.h
del core_main.cpp
del core_main.h
del core_phloat.cpp
del core_phloat.h
del core_sto_rcl.cpp
del core_sto_rcl.h
del core_tables.cpp
del core_tables.h
del core_variables.cpp
del core_variables.h
del shell.h
del shell_loadimage.cpp
del shell_loadimage.h
del shell_spool.cpp
del shell_spool.h
del skin2cpp.cpp
del skin2cpp.conf
del keymap2cpp.cpp
del bid_conf.h
del bid_functions.h
rmdir /s /q IntelRDFPMathLib20U1
del readtest.c
del readtest_lines.cpp
del cl111libbid.lib
