mklink /h free42.h ..\common\free42.h
mklink /h core_commands1.cpp ..\common\core_commands1.cc
mklink /h core_commands1.h ..\common\core_commands1.h
mklink /h core_commands2.cpp ..\common\core_commands2.cc
mklink /h core_commands2.h ..\common\core_commands2.h
mklink /h core_commands3.cpp ..\common\core_commands3.cc
mklink /h core_commands3.h ..\common\core_commands3.h
mklink /h core_commands4.cpp ..\common\core_commands4.cc
mklink /h core_commands4.h ..\common\core_commands4.h
mklink /h core_commands5.cpp ..\common\core_commands5.cc
mklink /h core_commands5.h ..\common\core_commands5.h
mklink /h core_commands6.cpp ..\common\core_commands6.cc
mklink /h core_commands6.h ..\common\core_commands6.h
mklink /h core_commands7.cpp ..\common\core_commands7.cc
mklink /h core_commands7.h ..\common\core_commands7.h
mklink /h core_display.cpp ..\common\core_display.cc
mklink /h core_display.h ..\common\core_display.h
mklink /h core_globals.cpp ..\common\core_globals.cc
mklink /h core_globals.h ..\common\core_globals.h
mklink /h core_helpers.cpp ..\common\core_helpers.cc
mklink /h core_helpers.h ..\common\core_helpers.h
mklink /h core_keydown.cpp ..\common\core_keydown.cc
mklink /h core_keydown.h ..\common\core_keydown.h
mklink /h core_linalg1.cpp ..\common\core_linalg1.cc
mklink /h core_linalg1.h ..\common\core_linalg1.h
mklink /h core_linalg2.cpp ..\common\core_linalg2.cc
mklink /h core_linalg2.h ..\common\core_linalg2.h
mklink /h core_math1.cpp ..\common\core_math1.cc
mklink /h core_math1.h ..\common\core_math1.h
mklink /h core_math2.cpp ..\common\core_math2.cc
mklink /h core_math2.h ..\common\core_math2.h
mklink /h core_main.cpp ..\common\core_main.cc
mklink /h core_main.h ..\common\core_main.h
mklink /h core_phloat.cpp ..\common\core_phloat.cc
mklink /h core_phloat.h ..\common\core_phloat.h
mklink /h core_sto_rcl.cpp ..\common\core_sto_rcl.cc
mklink /h core_sto_rcl.h ..\common\core_sto_rcl.h
mklink /h core_tables.cpp ..\common\core_tables.cc
mklink /h core_tables.h ..\common\core_tables.h
mklink /h core_variables.cpp ..\common\core_variables.cc
mklink /h core_variables.h ..\common\core_variables.h
mklink /h shell.h ..\common\shell.h
mklink /h shell_loadimage.cpp ..\common\shell_loadimage.cc
mklink /h shell_loadimage.h ..\common\shell_loadimage.h
mklink /h shell_spool.cpp ..\common\shell_spool.cc
mklink /h shell_spool.h ..\common\shell_spool.h
mklink /h skin2cpp.cpp ..\common\skin2cc.cc
mklink /h skin2cpp.conf ..\common\skin2cc.conf
mklink /h keymap2cpp.cpp ..\common\keymap2cc.cc
mklink /h bid_conf.h ..\common\bid_conf.h
mklink /h bid_functions.h ..\common\bid_functions.h
