#!/bin/sh -x
./skin2prc -layout "$1" \
	    -gif "$2" \
	    -script tmp_skin.sh \
	    -rcp tmp_skin.rcp \
	    -skin_id $3 \
	    -bitmap_id $4 \
	    -depths $5 \
	    -density $6 \
	    -name $7 \
	    -dither $8 \
	    -sections $9
sh tmp_skin.sh
pilrc -q -ro -o $7.prc -type Skin -creator Fk42 -name $7 tmp_skin.rcp
rm tmp_skin.*
