#!/bin/sh -e

mkdir -p packages

cd iphone
rm -rf build/Distribution-iphoneos
echo "======== ATTENTION: Possible Password Prompt ========"
security unlock-keychain /Users/thomas/Library/Keychains/login.keychain
xcodebuild -project Free42.xcodeproj -target Free42 -configuration Distribution build
cd build/Distribution-iphoneos
zip -r --symlinks ../../../packages/Free42.app.zip Free42.app
cd ../../..
