#!/bin/sh -e

# This script builds the GTK version.

PKGNAME=Free42`uname -s`

if [ -f /usr/include/alsa/asoundlib.h ]; then
  ALSA='AUDIO_ALSA=1'
else
  ALSA=
fi

if [ -z $MK ]; then
  if which gmake > /dev/null; then
    MK=gmake
  else
    MK=make
  fi
fi
export MK

unset BCD_MATH
cd gtk
$MK cleaner
$MK -j 6 $ALSA
$MK clean
$MK -j 6 BCD_MATH=1 $ALSA
cd ..

rm -rf $PKGNAME
mkdir $PKGNAME
cp gtk/README $PKGNAME
cp gtk/free42bin $PKGNAME
cp gtk/free42dec $PKGNAME
cp gtk/icon-128x128.xpm $PKGNAME/free42icon-128x128.xpm
strip $PKGNAME/free42bin
strip $PKGNAME/free42dec
mkdir -p packages
tar cvfz packages/$PKGNAME.tgz $PKGNAME
rm -rf $PKGNAME
