#!/bin/sh -e

unset BCD_MATH
if [ -f /usr/include/alsa/asoundlib.h ]; then
  ALSA='AUDIO_ALSA=1'
else
  ALSA=
fi
PKGNAME=Free42`uname -s`

if [ -z $MK ]; then
  which gmake >/dev/null
  if [ $? -eq 0 ]; then
    MK=gmake
  else
    MK=make
  fi
fi
export MK

cd gtk
$MK cleaner
$MK -e $ALSA
$MK clean
$MK -e BCD_MATH=1 $ALSA
cd ..

rm -rf $PKGNAME
mkdir $PKGNAME
cp gtk/README $PKGNAME
cp gtk/free42bin $PKGNAME
cp gtk/free42dec $PKGNAME
strip $PKGNAME/free42bin
strip $PKGNAME/free42dec
mkdir -p packages
tar cvfz packages/$PKGNAME.tgz $PKGNAME
rm -rf $PKGNAME
