#!/bin/sh -e

# This script builds and packages the Windows and Android versions,
# and the Generic, iPhone, and Android skins packages, and the Upstream
# source package.
# It should be run in a Cygwin bash shell (under MS Windows, obviously).

unset BCD_MATH
mkdir -p packages

# Build Windows version

echo "NOTE: Windows command-line build needs to be rewritten using msbuild."
#cd windows
#cmd /c build-all.bat
#cd ..
#rm -rf Free42Windows
#mkdir Free42Windows
#cp windows/README.txt Free42Windows
#cp windows/ReleaseBinary/Free42Binary.exe Free42Windows
#cp windows/ReleaseDecimal/Free42Decimal.exe Free42Windows
#zip -r packages/Free42Windows.zip Free42Windows
#rm -rf Free42Windows

# Build Android version

mkdir android-tmp
cd android-tmp
svn checkout svn://macmini/free42/trunk free42
cd free42/android
sed 's/android:debuggable="[^"]*"/android:debuggable="false"/' < AndroidManifest.xml > TMP
mv TMP AndroidManifest.xml
VERSION_CODE=`cat version.code`
VERSION_CODE=`expr $VERSION_CODE + 1`
echo $VERSION_CODE > version.code
svn commit -m 'Automatic version.code bump' version.code
sed "s/android:versionCode=\"[^\"]*\"/android:versionCode=\"$VERSION_CODE\"/" < AndroidManifest.xml > TMP
mv TMP AndroidManifest.xml
VERSION_NAME=`cat ../VERSION`
sed "s/android:versionName=\"[^\"]*\"/android:versionName=\"$VERSION_NAME\"/" < AndroidManifest.xml > TMP
mv TMP AndroidManifest.xml
cd jni
sh ./copy-files-release.sh
/cygdrive/c/android-ndk-r4/ndk-build
cd ..
echo "======== ATTENTION: Possible Password Prompt ========"
ant release
mv bin/Free42Android-release.apk ../../../packages/Free42Android.apk
cd ../../..
rm -rf android-tmp

# Source package, and Windows/Unix skins packages
mkdir tmp
cd tmp
svn checkout svn://macmini/free42/trunk free42
find . -type d -name .svn -prune -exec rm -rf {} \;
zip -j ../packages/Free42Skins.zip free42/skins/*
zip -j ../packages/Free42iPhoneSkins.zip free42/iphoneskins/*
zip -j ../packages/Free42AndroidSkins.zip free42/androidskins/*
tar cvfz ../packages/free42.tgz free42
cd ..
rm -rf tmp

# "Upstream" source package, for Fedora or other Linux distros
# Has all non-Linux versions, and all skins containing the HP logo, removed
cd upstream
sh ./build-upstream
cd ..

# Wrap it all up...
cd util
cc -o txt2html txt2html.c
cd ..
util/txt2html "Free42 HISTORY" <HISTORY >history.html
util/txt2html "Free42 TODO" <TODO >todo.html
mv history.html todo.html packages
