#!/bin/sh -e
  
# This script builds and packages the Android version.

mkdir -p packages

cd android/app/src/main/cpp
sh ./link-files.sh
sh ./build-intel-lib.sh
cd ../../../..
./gradlew --warning-mode all assembleRelease
mv app/build/outputs/apk/release/app-release.apk ../packages/Free42Android.apk
