#!/bin/sh -e

mkdir -p packages

cd mac
rm -rf "build/Release Binary"
rm -rf "build/Release Decimal"
xcodebuild -project Free42.xcodeproj -target Free42 -configuration "Release Binary" build
xcodebuild -project Free42.xcodeproj -target Free42 -configuration "Release Decimal" build
mkdir tmp
mv "build/Release Binary/Free42.app" "tmp/Free42 Binary.app"
mv "build/Release Decimal/Free42.app" "tmp/Free42 Decimal.app"
cp README.txt tmp
cd tmp
zip -r ../../packages/Free42Mac.zip "Free42 Binary.app" "Free42 Decimal.app" README.txt
cd ..
rm -rf tmp
cd ..

unset BCD_MATH
cd macdashboard
make clean
make
zip -r ../Free42Binary.zip Free42.wdgt
make clean
make -e BCD_MATH=1
zip -r ../Free42Decimal.zip Free42.wdgt
cd ..
zip packages/Free42MacDashboard.zip Free42Binary.zip Free42Decimal.zip
rm Free42Binary.zip Free42Decimal.zip

mkdir android-tmp
cd android-tmp
cvs checkout free42
cd free42/android
sed 's/android:debuggable="[^"]*"/android:debuggable="false"/' < AndroidManifest.xml > TMP
mv TMP AndroidManifest.xml
# TODO: version number & version code
cd jni
# TODO: copy files from ../common instead of ~/free42/common
sh ./copy-files.sh
/android-ndk-r4b/ndk-build
cd ..
ant release
mv bin/Free42Android-release.apk ../../../packages/Free42Android.apk
cd ../../..
rm -rf android-tmp
