#!/bin/sh -e

# This script builds the MacOS application, and upstream source package
# for MacPorts.
# If the -u option is specified, skips creation of the upstream package.

if [ $# -ge 1 -a "$1" = "-u" ]
then
    SKIP_UPSTREAM=1
    shift
else
    SKIP_UPSTREAM=0
fi

mkdir -p packages

cd mac
rm -rf "build/Release Binary"
rm -rf "build/Release Decimal"
xcodebuild -project Free42.xcodeproj -target Free42 -configuration "Release Binary" build
xcodebuild -project Free42.xcodeproj -target Free42 -configuration "Release Decimal" build
mkdir tmp
mv "build/Release Binary/Free42.app" "tmp/Free42 Binary.app"
mv "build/Release Decimal/Free42.app" "tmp/Free42 Decimal.app"
codesign -f -s "Developer ID Application: Thomas Okken (F4D88K2P5W)" "tmp/Free42 Binary.app"
codesign -f -s "Developer ID Application: Thomas Okken (F4D88K2P5W)" "tmp/Free42 Decimal.app"
cp README.txt tmp
cd tmp
zip -r ../../packages/Free42Mac.zip "Free42 Binary.app" "Free42 Decimal.app" README.txt
cd ..
rm -rf tmp
cd ..

# "Upstream" source package, for MacPorts.
# Has all non-Mac versions, and all skins containing the HP logo, removed
if [ $SKIP_UPSTREAM -eq 0 ]
then
    cd upstream
    sh ./build-macports
    cd ..
fi

echo "Remember to get Free42Mac.zip notarized before uploading!"
