#!/bin/sh -e

mkdir -p packages

unset BCD_MATH
cd macdashboard
make clean
make
zip -r ../Free42Binary.zip Free42.wdgt
make clean
make -e BCD_MATH=1
zip -r ../Free42Decimal.zip Free42.wdgt
cd ..
zip packages/Free42MacDashboard.zip Free42Binary.zip Free42Decimal.zip
rm Free42Binary.zip Free42Decimal.zip
