#!/bin/sh -e
  
# This script builds and packages the Android version.

mkdir -p packages

mkdir android-tmp
cd android-tmp
svn checkout svn://mactv/free42/trunk free42
cd free42/android/app
read -p "Keystore Password: " SPWD
sed -i '' "s/storePassword '[^']*'/storePassword '$SPWD'/" build.gradle
read -p "Key Password: " KPWD
sed -i '' "s/keyPassword '[^']*'/keyPassword '$KPWD'/" build.gradle
cd src/main/cpp
sh ./link-files-release.sh
sh ./build-intel-lib.sh
cd ../../../..
./gradlew --warning-mode all assembleRelease
mv app/build/outputs/apk/release/app-release.apk ../../../packages/Free42Android.apk
cd ../../..
rm -rf android-tmp
