#!/bin/sh -e

# This script builds the upstream source packages,
# and a minimally HTMLified version of HISTORY.
# If the -u option is specified, skips creation of the upstream packages.

if [ $# -ge 1 -a "$1" = "-u" ]
then
    SKIP_UPSTREAM=1
    shift
else
    SKIP_UPSTREAM=0
fi

mkdir -p packages

# "Upstream" source package, for Fedora or other Linux distros
# Has all non-Linux versions, and all skins containing the HP logo, removed
if [ $SKIP_UPSTREAM -eq 0 ]
then
    cd upstream
    sh ./build-nologo
    sh ./build-macports
    cd ..
fi

# Wrap it all up...
cd util
cc -o txt2html txt2html.c
cd ..
util/txt2html "Free42 history" <HISTORY >history.html
mv history.html packages
