#!/bin/sh -e

# This script builds the GTK version, and upstream source package.
# If the -u option is specified, skips creation of the upstream package.

if [ $# -ge 1 -a "$1" = "-u" ]
then
    SKIP_UPSTREAM=1
    shift
else
    SKIP_UPSTREAM=0
fi

PKGNAME=Free42`uname -s`

if [ -f /usr/include/alsa/asoundlib.h ]; then
  ALSA='AUDIO_ALSA=1'
else
  ALSA=
fi

if [ -z $MK ]; then
  which gmake >/dev/null
  if [ $? -eq 0 ]; then
    MK=gmake
  else
    MK=make
  fi
fi
export MK

unset BCD_MATH
cd gtk
$MK cleaner
$MK $ALSA
$MK clean
$MK BCD_MATH=1 $ALSA
cd ..

rm -rf $PKGNAME
mkdir $PKGNAME
cp gtk/README $PKGNAME
cp gtk/free42bin $PKGNAME
cp gtk/free42dec $PKGNAME
cp gtk/icon-128x128.xpm $PKGNAME/free42icon-128x128.xpm
strip $PKGNAME/free42bin
strip $PKGNAME/free42dec
mkdir -p packages
tar cvfz packages/$PKGNAME.tgz $PKGNAME
rm -rf $PKGNAME

# "Upstream" source package, for Fedora and other package builders.
# Has all non-GTK versions, and all skins containing the HP logo, removed.
if [ $SKIP_UPSTREAM -eq 0 ]
then
    cd upstream
    sh ./build-nologo
    cd ..
fi
