#!/bin/sh -x
rm -rf Free42PalmOS* Free42Windows* Free42Linux* tmp free42.tgz Free42Skins.zip Free42PalmOSSkins.zip

# PalmOS package
mkdir Free42PalmOS
cp palmos/README.txt Free42PalmOS
cp palmos/free42bin.prc Free42PalmOS
cp palmos/free42dec.prc Free42PalmOS
cp conduit/Free42ConduitInstaller/Release/Free42ConduitInstaller.exe Free42PalmOS
cp conduit/Free42Conduit/Release/Free42Conduit.dll Free42PalmOS
cp /win/cdk403/Common/Bin/condmgr.dll Free42PalmOS
cp /win/cdk403/Common/Bin/HSAPI.dll Free42PalmOS
zip -r Free42PalmOS.zip Free42PalmOS
rm -rf Free42PalmOS

# Windows package -- Visual C++
mkdir Free42Windows
cp windows/README.txt Free42Windows
cp windows/ReleaseBinary/Free42Binary.exe Free42Windows
cp windows/ReleaseDecimal/Free42Decimal.exe Free42Windows
zip -r Free42Windows.zip Free42Windows
rm -rf Free42Windows

# Windows package -- MinGW
# mkdir Free42Windows
# cp windows/README.txt Free42Windows
# cp windows/Free42Binary.exe Free42Windows
# cp windows/Free42Decimal.exe Free42Windows
# /mingw/bin/strip windows/Free42Binary.exe
# /mingw/bin/strip windows/Free42Decimal.exe
# zip -r Free42Windows.zip Free42Windows
# rm -rf Free42Windows

# Linux package
mkdir Free42Linux
cp motif/README Free42Linux
cp motif/free42bin Free42Linux
cp motif/free42dec Free42Linux
strip Free42Linux/free42bin
strip Free42Linux/free42dec
tar cvfz Free42Linux.tgz Free42Linux
rm -rf Free42Linux

# Source package
mkdir tmp
cd tmp
cvs checkout free42
find . -type d -name CVS -prune -exec rm -rf {} \;
zip -j ../Free42Skins.zip free42/skins/*
tar cvfz ../free42.tgz free42
cd ..
rm -rf tmp

# Wrap it all up...
cp HISTORY HISTORY.txt
cp TODO TODO.txt
cp palmos/Free42PalmOSSkins.zip .
tar cvf package.tar Free42PalmOS.zip Free42Windows.zip Free42Linux.tgz free42.tgz Free42Skins.zip Free42PalmOSSkins.zip HISTORY.txt TODO.txt
rm Free42PalmOS.zip Free42Windows.zip Free42Linux.tgz free42.tgz Free42Skins.zip Free42PalmOSSkins.zip HISTORY.txt TODO.txt
