#!/bin/sh -e

# Rebuild everything (except for the stuff that needs to be built with
# MSVC++, i.e. the Windows versions and the PalmOS Conduit + Installer).
unset BCD_MATH
cd palmos
make cleaner
make
make clean
make -e BCD_MATH=1
make Free42PalmOSSkins.zip
cd ../gtk
make cleaner
make
make clean
make -e BCD_MATH=1
cd ../motif
make cleaner
make
make clean
make -e BCD_MATH=1
cd ..

# Clean up crap that may have been left lying around
rm -rf Free42PalmOS* Free42Windows* Free42Linux* tmp free42.tgz Free42Skins.zip Free42PalmOSSkins.zip history.html todo.html

# PalmOS package
mkdir Free42PalmOS
cp palmos/README.txt Free42PalmOS
cp palmos/free42bin.prc Free42PalmOS
cp palmos/free42dec.prc Free42PalmOS
cp conduit/Free42ConduitInstaller/Release/Free42ConduitInstaller.exe Free42PalmOS
cp conduit/Free42Conduit/Release/Free42Conduit.dll Free42PalmOS
cp /win/cdk403/Common/Bin/condmgr.dll Free42PalmOS
cp /win/cdk403/Common/Bin/HSAPI.dll Free42PalmOS
zip -r Free42PalmOS.zip Free42PalmOS
rm -rf Free42PalmOS

# Windows package -- Visual C++
mkdir Free42Windows
cp windows/README.txt Free42Windows
cp windows/ReleaseBinary/Free42Binary.exe Free42Windows
cp windows/ReleaseDecimal/Free42Decimal.exe Free42Windows
zip -r Free42Windows.zip Free42Windows
rm -rf Free42Windows

# Windows package -- MinGW
# mkdir Free42Windows
# cp windows/README.txt Free42Windows
# cp windows/Free42Binary.exe Free42Windows
# cp windows/Free42Decimal.exe Free42Windows
# /mingw/bin/strip windows/Free42Binary.exe
# /mingw/bin/strip windows/Free42Decimal.exe
# zip -r Free42Windows.zip Free42Windows
# rm -rf Free42Windows

# Linux package
mkdir Free42Linux
mkdir Free42Linux/gtk
mkdir Free42Linux/motif
cp gtk/README Free42Linux/gtk
cp gtk/free42bin Free42Linux/gtk
cp gtk/free42dec Free42Linux/gtk
strip Free42Linux/gtk/free42bin
strip Free42Linux/gtk/free42dec
cp motif/README Free42Linux/motif
cp motif/free42bin Free42Linux/motif
cp motif/free42dec Free42Linux/motif
strip Free42Linux/motif/free42bin
strip Free42Linux/motif/free42dec
tar cvfz Free42Linux.tgz Free42Linux
rm -rf Free42Linux

# Source package
mkdir tmp
cd tmp
cvs checkout free42
find . -type d -name CVS -prune -exec rm -rf {} \;
zip -j ../Free42Skins.zip free42/skins/*
zip -j ../Free42PocketPCSkins.zip free42/ppcskins/*
tar cvfz ../free42.tgz free42
cd ..
rm -rf tmp

# Wrap it all up...
cd util
cc -o txt2html txt2html.c
cd ..
util/txt2html "Free42 HISTORY" <HISTORY >history.html
util/txt2html "Free42 TODO" <TODO >todo.html
cp palmos/Free42PalmOSSkins.zip .
tar cvf package.tar Free42PalmOS.zip Free42Windows.zip Free42Linux.tgz free42.tgz Free42Skins.zip Free42PocketPCSkins.zip Free42PalmOSSkins.zip history.html todo.html
rm Free42PalmOS.zip Free42Windows.zip Free42Linux.tgz free42.tgz Free42Skins.zip Free42PocketPCSkins.zip Free42PalmOSSkins.zip history.html todo.html
