/**
 ******************************************************************************
 * @file      syscalls.c
 * @author    Auto-generated by STM32CubeIDE
 * @brief     STM32CubeIDE Minimal System calls file
 *
 *            For more information about which c-functions
 *            need which of these lowlevel functions
 *            please consult the Newlib libc-manual
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2020-2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* Includes */
#include <sys/stat.h>
#include <stdlib.h>
#include <errno.h>
#include <stdio.h>
#include <signal.h>
#include <time.h>
#include <sys/time.h>
#include <sys/times.h>

#include "rp/RP.hh"

/* Variables */
extern int __io_putchar(int ch) __attribute__((weak));
extern int __io_getchar(void) __attribute__((weak));


char *__env[1] = { 0 };
char **environ = __env;


/* Functions */
void initialise_monitor_handles()
{
}

int _getpid(void)
{
  return 1;
}

int _kill(int pid, int sig)
{
  if (pid == 1) {
	  _exit(sig);
	  return 0;
  }

  return -1;
}

void _exit (int status)
{
  RP_EXIT(status);
  while (1) {}    /* Make sure we hang here */
}

__attribute__((weak)) int _read(int file, char *ptr, int len)
{
  uint32_t bytesRead;

  RP_FREAD((RP_FILE) file, ptr, len, &bytesRead);

  return bytesRead;
}

__attribute__((weak)) int _write(int file, char *ptr, int len)
{
	uint32_t bytesWritten;
	RP_FWRITE((RP_FILE) file, ptr, len, &bytesWritten);

	return bytesWritten;
}

int _close(int file)
{
  return RP_FCLOSE(file);
}


int _fstat(int file, struct stat *st)
{
  return RP_FSTAT(file, st);
}

int _isatty(int file)
{
  if (file >= 0 && file <= 2) return 1;
  return 0;
}

int _lseek(int file, int ptr, int dir)
{
 return RP_FSEEK((RP_FILE) file, ptr, dir);
}

int _open(char *path, int flags, ...)
{
  int handle;
  RP_FOPEN(&handle, path, flags);

  return handle;
}

int _wait(int *status)
{
  (void)status;
  errno = ECHILD;
  return -1;
}

int _unlink(char *name)
{
  return RP_UNLINK(name);
}

int _times(struct tms *buf)
{
  (void)buf;
  return -1;
}

int _stat(char *file, struct stat *st)
{
  return RP_STAT(file, st);
}

int _link(char *old, char *new)
{
  (void)old;
  (void)new;
  errno = EMLINK;
  return -1;
}

int _fork(void)
{
  errno = EAGAIN;
  return -1;
}

int _execve(char *name, char **argv, char **env)
{
  (void)name;
  (void)argv;
  (void)env;
  errno = ENOMEM;
  return -1;
}
