#!/bin/sh
cp ~/free42/common/bid_conf.h bid_conf.h
cp ~/free42/common/bid_functions.h bid_functions.h
cp ~/free42/common/core_commands1.cc core_commands1.cc
cp ~/free42/common/core_commands1.h core_commands1.h
cp ~/free42/common/core_commands2.cc core_commands2.cc
cp ~/free42/common/core_commands2.h core_commands2.h
cp ~/free42/common/core_commands3.cc core_commands3.cc
cp ~/free42/common/core_commands3.h core_commands3.h
cp ~/free42/common/core_commands4.cc core_commands4.cc
cp ~/free42/common/core_commands4.h core_commands4.h
cp ~/free42/common/core_commands5.cc core_commands5.cc
cp ~/free42/common/core_commands5.h core_commands5.h
cp ~/free42/common/core_commands6.cc core_commands6.cc
cp ~/free42/common/core_commands6.h core_commands6.h
cp ~/free42/common/core_commands7.cc core_commands7.cc
cp ~/free42/common/core_commands7.h core_commands7.h
cp ~/free42/common/core_display.cc core_display.cc
cp ~/free42/common/core_display.h core_display.h
cp ~/free42/common/core_globals.cc core_globals.cc
cp ~/free42/common/core_globals.h core_globals.h
cp ~/free42/common/core_helpers.cc core_helpers.cc
cp ~/free42/common/core_helpers.h core_helpers.h
cp ~/free42/common/core_keydown.cc core_keydown.cc
cp ~/free42/common/core_keydown.h core_keydown.h
cp ~/free42/common/core_linalg1.cc core_linalg1.cc
cp ~/free42/common/core_linalg1.h core_linalg1.h
cp ~/free42/common/core_linalg2.cc core_linalg2.cc
cp ~/free42/common/core_linalg2.h core_linalg2.h
cp ~/free42/common/core_main.cc core_main.cc
cp ~/free42/common/core_main.h core_main.h
cp ~/free42/common/core_math1.cc core_math1.cc
cp ~/free42/common/core_math1.h core_math1.h
cp ~/free42/common/core_math2.cc core_math2.cc
cp ~/free42/common/core_math2.h core_math2.h
cp ~/free42/common/core_phloat.cc core_phloat.cc
cp ~/free42/common/core_phloat.h core_phloat.h
cp ~/free42/common/core_sto_rcl.cc core_sto_rcl.cc
cp ~/free42/common/core_sto_rcl.h core_sto_rcl.h
cp ~/free42/common/core_tables.cc core_tables.cc
cp ~/free42/common/core_tables.h core_tables.h
cp ~/free42/common/core_variables.cc core_variables.cc
cp ~/free42/common/core_variables.h core_variables.h
cp ~/free42/common/free42.h free42.h
cp ~/free42/common/shell.h shell.h
cp ~/free42/common/shell_spool.cc shell_spool.cc
cp ~/free42/common/shell_spool.h shell_spool.h
