#!/bin/sh
ln -s ~/free42/common/bid_conf.h
ln -s ~/free42/common/bid_functions.h
ln -s ~/free42/common/core_commands1.cc
ln -s ~/free42/common/core_commands1.h
ln -s ~/free42/common/core_commands2.cc
ln -s ~/free42/common/core_commands2.h
ln -s ~/free42/common/core_commands3.cc
ln -s ~/free42/common/core_commands3.h
ln -s ~/free42/common/core_commands4.cc
ln -s ~/free42/common/core_commands4.h
ln -s ~/free42/common/core_commands5.cc
ln -s ~/free42/common/core_commands5.h
ln -s ~/free42/common/core_commands6.cc
ln -s ~/free42/common/core_commands6.h
ln -s ~/free42/common/core_commands7.cc
ln -s ~/free42/common/core_commands7.h
ln -s ~/free42/common/core_display.cc
ln -s ~/free42/common/core_display.h
ln -s ~/free42/common/core_globals.cc
ln -s ~/free42/common/core_globals.h
ln -s ~/free42/common/core_helpers.cc
ln -s ~/free42/common/core_helpers.h
ln -s ~/free42/common/core_keydown.cc
ln -s ~/free42/common/core_keydown.h
ln -s ~/free42/common/core_linalg1.cc
ln -s ~/free42/common/core_linalg1.h
ln -s ~/free42/common/core_linalg2.cc
ln -s ~/free42/common/core_linalg2.h
ln -s ~/free42/common/core_main.cc
ln -s ~/free42/common/core_main.h
ln -s ~/free42/common/core_math1.cc
ln -s ~/free42/common/core_math1.h
ln -s ~/free42/common/core_math2.cc
ln -s ~/free42/common/core_math2.h
ln -s ~/free42/common/core_phloat.cc
ln -s ~/free42/common/core_phloat.h
ln -s ~/free42/common/core_sto_rcl.cc
ln -s ~/free42/common/core_sto_rcl.h
ln -s ~/free42/common/core_tables.cc
ln -s ~/free42/common/core_tables.h
ln -s ~/free42/common/core_variables.cc
ln -s ~/free42/common/core_variables.h
ln -s ~/free42/common/free42.h
ln -s ~/free42/common/shell.h
ln -s ~/free42/common/shell_spool.cc
ln -s ~/free42/common/shell_spool.h
