#!/bin/sh
cp bid_conf.h ~/free42/common/bid_conf.h
cp bid_functions.h ~/free42/common/bid_functions.h
cp core_commands1.cc ~/free42/common/core_commands1.cc
cp core_commands1.h ~/free42/common/core_commands1.h
cp core_commands2.cc ~/free42/common/core_commands2.cc
cp core_commands2.h ~/free42/common/core_commands2.h
cp core_commands3.cc ~/free42/common/core_commands3.cc
cp core_commands3.h ~/free42/common/core_commands3.h
cp core_commands4.cc ~/free42/common/core_commands4.cc
cp core_commands4.h ~/free42/common/core_commands4.h
cp core_commands5.cc ~/free42/common/core_commands5.cc
cp core_commands5.h ~/free42/common/core_commands5.h
cp core_commands6.cc ~/free42/common/core_commands6.cc
cp core_commands6.h ~/free42/common/core_commands6.h
cp core_commands7.cc ~/free42/common/core_commands7.cc
cp core_commands7.h ~/free42/common/core_commands7.h
cp core_display.cc ~/free42/common/core_display.cc
cp core_display.h ~/free42/common/core_display.h
cp core_globals.cc ~/free42/common/core_globals.cc
cp core_globals.h ~/free42/common/core_globals.h
cp core_helpers.cc ~/free42/common/core_helpers.cc
cp core_helpers.h ~/free42/common/core_helpers.h
cp core_keydown.cc ~/free42/common/core_keydown.cc
cp core_keydown.h ~/free42/common/core_keydown.h
cp core_linalg1.cc ~/free42/common/core_linalg1.cc
cp core_linalg1.h ~/free42/common/core_linalg1.h
cp core_linalg2.cc ~/free42/common/core_linalg2.cc
cp core_linalg2.h ~/free42/common/core_linalg2.h
cp core_main.cc ~/free42/common/core_main.cc
cp core_main.h ~/free42/common/core_main.h
cp core_math1.cc ~/free42/common/core_math1.cc
cp core_math1.h ~/free42/common/core_math1.h
cp core_math2.cc ~/free42/common/core_math2.cc
cp core_math2.h ~/free42/common/core_math2.h
cp core_phloat.cc ~/free42/common/core_phloat.cc
cp core_phloat.h ~/free42/common/core_phloat.h
cp core_sto_rcl.cc ~/free42/common/core_sto_rcl.cc
cp core_sto_rcl.h ~/free42/common/core_sto_rcl.h
cp core_tables.cc ~/free42/common/core_tables.cc
cp core_tables.h ~/free42/common/core_tables.h
cp core_variables.cc ~/free42/common/core_variables.cc
cp core_variables.h ~/free42/common/core_variables.h
cp free42.h ~/free42/common/free42.h
cp shell.h ~/free42/common/shell.h
cp shell_spool.cc ~/free42/common/shell_spool.cc
cp shell_spool.h ~/free42/common/shell_spool.h
