#!/bin/sh
rm -rf temp
mkdir temp
cd temp
git clone --local ../.. free42
for i in `cat ../macports/remove`
do
    rm -rf free42/$i
done
( cd ../macports/replace ; tar cf - . ) | ( cd free42 ; tar xf - )
rm -rf free42/.git
mkdir -p ../../packages

VERSION=`awk 'f{print;f=0} /CFBundleVersion/{f=1}' free42/mac/Info.plist | sed 's/^.*>\([^<]*\)<.*$/\1/'`
if [[ $VERSION =~ \..*\..*\. ]]
then
    VERSION=`echo $VERSION | awk -F. '{printf "%d.%d.%d%c", $1, $2, $3, ($4 + 96)}'`
fi

PKGNAME=free42-macports-$VERSION
mv free42 $PKGNAME
tar cvfz ../../packages/$PKGNAME.tgz $PKGNAME
cd ..
rm -rf temp
