#!/bin/sh
rm -rf temp
mkdir temp
cd temp
svn checkout svn://mactv/free42/trunk free42
for i in `cat ../nologo/remove`
do
    rm -rf free42/$i
done
( cd ../nologo/replace ; tar cf - . ) | ( cd free42 ; tar xf - )
find . -type d -name .svn -prune -exec rm -rf {} \;
rm -rf free42/util/icon
mkdir -p ../../packages
PKGNAME=free42-nologo-`cat ../../VERSION`
mv free42 $PKGNAME
tar cvfz ../../packages/$PKGNAME.tgz $PKGNAME
cd ..
rm -rf temp
