#!/bin/sh
rm -rf temp
mkdir temp
cd temp
git clone --local ../.. free42
for i in `cat ../nologo/remove`
do
    rm -rf free42/$i
done
( cd ../nologo/replace ; tar cf - . ) | ( cd free42 ; tar xf - )
rm -rf free42/.git
mkdir -p ../../packages
PKGNAME=free42-nologo-`cat ../../gtk/VERSION`
mv free42 $PKGNAME
tar cvfz ../../packages/$PKGNAME.tgz $PKGNAME
cd ..
rm -rf temp
