#!/bin/sh -e

unset BCD_MATH
cd gtk
make cleaner
make -e AUDIO_ALSA=1
make clean
make -e BCD_MATH=1 AUDIO_ALSA=1
cd ..
rm -rf Free42Linux
mkdir Free42Linux
cp gtk/README Free42Linux
cp gtk/free42bin Free42Linux
cp gtk/free42dec Free42Linux
strip Free42Linux/free42bin
strip Free42Linux/free42dec
tar cvfz Free42Linux.tgz Free42Linux
rm -rf Free42Linux
